/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [31.94KB] > C:\Users\ferna\Downloads\book_set_gltf\scene-transformed.glb [599.12KB] (-1776%)
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Circle(props) {
  const { nodes, materials, animations } = useGLTF('/models/circle-transformed.glb')

  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
    // console.log(state.clock)
    modelRef.current.position.y = 0 + Math.sin(state.clock.elapsedTime) * 0.15;
    modelRef.current.rotation.z += delta * 0.3
  })

  const { actions } = useAnimations(animations)
  return (
    <group {...props} dispose={null}
    ref={modelRef}
            position={[0, -1.5, 0]}
            scale={[0.04, 0.04, 0.04]}
            rotation={[1.5, 0, 0]}
    >
      <mesh geometry={nodes.base_magic_circle_0.geometry} material={materials.magic_circle} />
    </group>
  )
}

useGLTF.preload('/models/circle-transformed.glb')
